# Generated by Django 4.0.6 on 2022-07-20 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_customer_owner_remove_user_owner_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Primary Key')),
                ('name', models.CharField(max_length=30, verbose_name='가게 이름')),
                ('introduction', models.TextField(verbose_name='가게 설명')),
                ('address', models.CharField(max_length=30, verbose_name='가게 주소')),
                ('number', models.CharField(max_length=30, verbose_name='가게 전화번호')),
                ('waiting_state', models.IntegerField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='accounts.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stroe_image')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='whytingapp.store')),
            ],
        ),
    ]
