# Generated by Django 4.0.6 on 2022-07-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whytingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='waiting_state',
            field=models.IntegerField(default='1'),
        ),
    ]
