# Generated by Django 4.0.6 on 2022-07-25 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whytingapp', '0002_alter_store_waiting_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='waiting_state',
            field=models.IntegerField(default=1),
        ),
    ]
