# Generated by Django 4.0.6 on 2022-07-20 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Primary Key')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Primary Key')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='user_owner',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_customer',
        ),
        migrations.DeleteModel(
            name='User_owner',
        ),
    ]
