# Generated by Django 4.0.6 on 2022-07-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whytingapp', '0003_alter_store_owner_id_alter_store_waiting_state'),
        ('accounts', '0005_alter_customer_id_alter_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
